# Generated by Django 6.0.1 on 2026-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alumnos/', verbose_name='Foto del Alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
