# Generated by Django 6.0.1 on 2026-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alumno_foto_alter_alumno_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='disciplinas',
            field=models.ManyToManyField(to='asistencia.disciplina', verbose_name='Disciplinas Inscritas'),
        ),
    ]
