# Generated by Django 6.0.1 on 2026-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_disciplina_pago_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Membresía'),
        ),
    ]
