# Generated by Django 6.0.1 on 2026-01-15 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alumno_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
    ]
